version: '3.4'

services:
  frontend_website_template3:
    container_name: frontend_website_template3
    build: .
    ports:
      - 1237:1234
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/usr/src/app/src
      - ./src/yarn.lock:/usr/src/app/src/yarn.lock