version: '3.4'

services:
  frontend_website_template:
    container_name: frontend_website_template
    build: .
    ports:
      - 1234:1234
    restart: unless-stopped
    volumes:
      - ./usr/src/app/
      # - ./usr/src/app/node_modules